name: Compile Code

on:
  push:
    branches:
      - '*' #Pusher til hvilket som helst branch

jobs:
  build:
    name: Compile Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Compile Code
        run: go build NBXBook.go #Kompilerer kode

      - name: Build Docker image
        run: docker build . --tag nbx

      - name: Push docker image if pushed to main
        if: github.ref == 'refs/heads/main'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin   
          docker tag nbx $DOCKERHUB_USERNAME/nbx
          docker push $DOCKERHUB_USERNAME/nbx:latest
