name: Compile Code

on:
  push:
    branches:
      - '*' #Pusher til hvilket som helst branch

jobs:
  build:
    name: Compile Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env: #Sercet environment variables
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          #Code below does 4 things:
          # 1. Logging in to docker
          # 2. Builds the project to a docker container
          # 3. Tags the project to docker hub (??)
          # 4. Pushes it to docker hub
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin   
          docker build . --tag nbx
          docker tag nbx $DOCKERHUB_USERNAME/nbx
          docker push $DOCKERHUB_USERNAME/nbx:latest

      - name: Compile Code
        run: go build NBXBook.go #Kompilerer kode